Feat: 일정 & 루틴 Domain 설계
toduck-App/iOS-to.duck pull request #19
Opened 2024-06-10 11:47 UTC by Kyxxn

## #️⃣ 연관된 이슈
close: #15 

## 📝 작업 내용
- 일정 & 루틴 Entity
- 일정 & 루틴 UseCase
- 일정 & 루틴 Repository Protocol
- 일정 & 루틴 Repository

2024-06-10 15:24 UTC, N-Joy-Shadow commented
괜찮은거 같습니다.

2024-06-10 15:57 UTC, Sonny-Kor approved these changes
확인했습니당

2024-06-11 05:22 UTC, N-Joy-Shadow requested changes

2024-06-11 06:28 UTC, Kyxxn commented on toduck/Source/Domain/Entity/DateUtils.swift
> +}
좋은 거 같습니당
수정했습니다 !

2024-06-11 06:29 UTC, N-Joy-Shadow approved these changes

2024-06-11 06:29 UTC, N-Joy-Shadow commented
확인 했습니다

2024-06-11 06:30 UTC, merged