feat: BaseCalendar & TDCalendarConfigurable 명확한 역할 분리 & SheetCalendar 구현
toduck-App/iOS-to.duck pull request #51
Opened 2024-09-01 14:05 UTC by Kyxxn

## #️⃣ 연관된 JIRA 이슈
- Jira TOD-107

## 📝 작업 내용
- BaseCalendar 클래스
    - 헤더 숨기기, 지역, 스크롤 방향 등 기본적인 캘린더의 기능을 넣음
- TDCalendarConfigurable 프로토콜
    - where Self: UIViewController를 통해 뷰컨트롤러만 채택하게 함
    - Delegate와 DataSource 지정 + CalendarHeaderStackView와 Calendar를 view에 넣어둠
    - associatedtype CalendarType: BaseCalendar을 통해 BaseCalendar를 따르는 모든 클래스에 대한 설정을 해줌
    - func updateHeaderLabel(): 달이 바뀌었을 때 호출되어, 캘린더 헤더의 "M월"이 바뀜
    - func colorForDate(): 오늘날짜, 토요일, 일요일은 각각 고유한 색이 있음, 특정 날짜가 선택됐을 때도 이 메소드를 호출해서 색 유지
- SheetCalendar
    - FSCalendar의 각각 날짜에 대한 셀은 `FSCalendarCell : UICollectionViewCell`임
    - 커스텀 SheetCalendarSelectDateCell을 만들어서 처리해줌
    <img width="303" alt="스크린샷 2024-09-01 오후 11 01 59" src="https://github.com/user-attachments/assets/0b2279ce-a608-40e3-994b-2fda59348f85">
    
    - 시작일의 경우 circleBackImageView와 rightRectBackImageView를 활성화
    - 중간의 경우 3개 다 활성화
    - 종료일의 경우 leftRectBackImageView와 circleBackImageView를 활성화
    - 시작일과 중간일의 경우 Primary500에 대한 circleBackImageView 추가
    - 최종이미지
    <img width="236" alt="스크린샷 2024-09-01 오후 11 04 50" src="https://github.com/user-attachments/assets/cd9984a7-8dac-4d8d-93e9-bdc2ab1a5d9e">

- TDLabel
    - required init의 fatalError 제거
    - init된 후에 setupAttributes 메소드가 호출되면 색상이 날라가는 경우가 발생
    - setupAttributes 메소드 내에서 텍스트에 색상 넣어주는 코드 추가

### ?? 고민된 부분 (아마 또 고민할듯)
- Delegate, DataSource 메소드 처리를 BaseCalendar에 둘지, TDCalendarConfigurable에 둘지 고민이었음
    - BaseCalendar에서 처리
        - FSCalendarDelegate, FSCalendarDataSource, FSCalendarDelegateAppearance를 다 채택하고 관련 메소드 미리 구현
        - ViewController의 프로퍼티에 의존적인 동작이 많았음
        Sheet의 경우, firstDate-lastDate가 위 프로토콜 메소드에서 필요, 그렇다고 매개변수로 프로퍼티를 받지도 못함
        - 또한, 결국 캘린더를 쓰는 뷰컨트롤러에서 위 프로토콜의 메소드를 써야할 일이 생겼음
        - 이러한 이유로 BaseCalendar에서 작업 X
    - TDCalendarConfigurable에서 처리
        - 위 프로토콜은 FSCalendarDelegate, FSCalendarDataSource, FSCalendarDelegateAppearance 채택만 하고,
        구현은 캘린더를 사용하는 뷰컨트롤러에서 사용하기
        - 뷰컨트롤러에서 위 3개 프로토콜 채택 안 하고 TDCalendarConfigurable 하나만 채택하면 됨
        - 뷰컨트롤러의 길이가 길어짐 -> 뷰모델로 나누면 좀 해결될듯

### 📺 실행 영상

https://github.com/user-attachments/assets/08e6cdf6-7171-4f76-bb3e-855fabd6abb4

### 보완할 점
- 뷰컨트롤러에서 날짜 로직을 처리하고 있어서, 뷰모델로 분리하려 했으나 calendar 프로퍼티가 없어서 여러 날짜가 지정된 경우, 중간 날짜 선택 및 해제가 어려웠음 -> 나중에 다시 처리하는 걸로
- 우측 상단에 선택된 날짜가 "시작일: 9월 1일 - 종료일: 10월 10일" 이라면, 어떻게 날짜 표현할 건지 디자이너한테 여쭤봐둠
- 아직 TDCalendar와 DiaryCalendar 작업이 안 되었음
    - TDCalendar의 경우, 스크롤이 필요할 거 같음
    - DiaryCalendar의 경우, 디자인이 바뀌어서 커스텀 셀 작업이 필요할듯

2024-09-02 01:53 UTC, Sonny-Kor commented on toduck/Source/Design/Component/CalendarView/Common/BaseCalendar.swift
> +        self.appearance.weekdayTextColor = TDColor.Neutral.neutral600
여기 indent가 이상해요

2024-09-02 01:58 UTC, Sonny-Kor commented on toduck/Source/Design/Component/CalendarView/Cell/SheetCalendarSelectDateCell.swift
> +	override init!(frame: CGRect) {
여기 init을 강제 언래핑 하는 이유가 있을까요 ?

2024-09-03 17:22 UTC, N-Joy-Shadow requested changes

2024-09-05 16:03 UTC, Kyxxn commented on toduck/Source/Design/Component/CalendarView/Cell/SheetCalendarSelectDateCell.swift
> +	override init!(frame: CGRect) {
왜인지 모르겠으나, 자동완성이 강제 언래핑이더라구요
수정해뒀습니다!

2024-09-05 16:04 UTC, Kyxxn commented on toduck/Source/Design/Component/CalendarView/Common/BaseCalendar.swift
> +        self.appearance.weekdayTextColor = TDColor.Neutral.neutral600
해결했습니다

2024-09-05 16:15 UTC, N-Joy-Shadow approved these changes

2024-09-07 06:40 UTC, Sonny-Kor approved these changes

2024-09-07 06:52 UTC, merged